version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/examples/secure-data-mcp-example/backend"
    schedule:
      interval: "weekly"
  # MCP Python project (pyproject.toml/uv)
  - package-ecosystem: "pip"
    directory: "/mcp/vaultmcp"
    schedule:
      interval: "weekly"
  # Root Node.js (if used)
  - package-ecosystem: "npm"
    directory: "/examples/secure-data-mcp-example"
    schedule:
      interval: "weekly"
  # Frontend Node.js
  - package-ecosystem: "npm"
    directory: "/examples/secure-data-mcp-example/frontend"
    schedule:
      interval: "weekly"
  # MCP server Node.js
  - package-ecosystem: "npm"
    directory: "/examples/secure-data-mcp-example/mcp-server"
    schedule:
      interval: "weekly"
  # Agentic Commerce Tutorial - Collect Card Data
  - package-ecosystem: "npm"
    directory: "/examples/agentic-commerce-tutorial/collect-card-data"
    schedule:
      interval: "weekly"
  # Agentic Commerce Tutorial - PSP Provisioner
  - package-ecosystem: "npm"
    directory: "/examples/agentic-commerce-tutorial/psp-provisioner"
    schedule:
      interval: "weekly"
  # MCP UI Collect - Frontend
  - package-ecosystem: "npm"
    directory: "/examples/mcp-ui-collect/frontend"
    schedule:
      interval: "weekly"
  # MCP UI Collect - Backend
  - package-ecosystem: "pip"
    directory: "/examples/mcp-ui-collect/backend"
    schedule:
      interval: "weekly" 
