name: VaultMCP Module Checks

on:
  push:
    paths:
      - 'mcp/vaultmcp/**'
  pull_request:
    paths:
      - 'mcp/vaultmcp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcp/vaultmcp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install .
      - name: Check Python files compile
        run: python -m compileall .
      # If you add tests, add a step here to run them, e.g. pytest 