name: Frontend Tests

on:
  push:
    paths:
      - 'examples/secure-data-mcp-example/frontend/**'
  pull_request:
    paths:
      - 'examples/secure-data-mcp-example/frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/secure-data-mcp-example/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test 